### ISSUE TITLE
[Login Page] Nothing happen a registered user login with Google login, 

### ISSUE THREAD

**Issue by upfounders** [upfounders/upfoundersAngular#1]
I tried to log in with my Gmail account, kaderjan@gmail.com, but after choosing my Gmail account from the Google popup, the popup closes, then nothing happens. 

what is the expected behaviour?
Based on my understanding, after authenticating with google, if the user is found in the DB, the user should be able to login to the app right?

**Comment by zaid4kspr** [comment]
if you want to login with google you can do it in one condition you should have connected with google for the first time, if you used the classic method (register with password) you need to register with email and password for the next times you want to login

**Comment by upfounders** [comment]
If a user wants to login in to the app with Google even if he/she has an account, can we overwrite his info with one from Google or at least let him login?

**Comment by zaid4kspr** [comment]
i will let him login if he have an account and now try to connect with google
