### ISSUE TITLE
[Sharing Contact] Full note of contact of a user shouldn't shared with another user

### ISSUE THREAD

**Issue by upfounders** [upfounders/upfoundersAngular#10]
Right now, when we user contacting, we create a duplicate of contact for the user we are sharing with, this is great! but we shouldn't share the full note, instead, all we have to do, replace the note of the contact with the message which is used when the contact is shared. For example, I shared a contact User B with you with the message "He is a great guy and well-skilled Mobile developer,", after you accepting this contact, the note of the contact showing for you would be "Kaderjan Ilghar shared this contact with you on 2/16/2020 4:00 pm with the message He is a great guy and well-skilled mobile developer" because the note of a contact is very personal for each user, it shouldn't shared.

**Comment by zaid4kspr** [comment]
so if user a share contact with user b, user b will get a note in wich we fin the text that you mentionned i made this possible and you can test it in the next update
