### ISSUE TITLE
[Login] There are some issue login experience 

### ISSUE THREAD

**Issue by upfounders** [upfounders/upfoundersAngular#11]
As I mentioned in the past, all login/registering user should be invited, they shouldn't be able to login/register without any invitation. 

The way, the app will be promoted will be starting with me inviting all the people in my connection, they got invited, and you get the privilege to register and invite others. 

Right now, if we invite users, the user got an email and the link takes the user register page, they register, and after register, they want to login with social instead of putting a password, they won't be able to log in.

Let's have a call on this make sure you have a clear understanding. I also need to understand how to Sign up with Google work.

**Comment by zaid4kspr** [comment]
i will let him login if he have an upfounders account and now try to connect with google
