### ISSUE TITLE
[Add Contact Page] Inviting contact while adding contacting

### ISSUE THREAD

**Issue by upfounders** [upfounders/upfoundersAngular#2]
Step 1: Logged in with kaderjan@gmail.com, selected to invite the contact while adding it (nilghar@gmail.com), email is received, clicked the link from the email, got redirected to the login page (we need to either bring people to register page or provide a better introduction, need to fix it, I will create a different issue for this). 

Step 2: Logged in with nilghar@gmail.com, was able to login to app, but the didn't see kaderjan@gmail.com is added as a contact

**Comment by zaid4kspr** [comment]
i forgot to update the link that we sent to the invited user in order to register, i updated the link in the mail and now the problem should be solved

**Comment by upfounders** [comment]
How about the issue in Step 2?

**Comment by zaid4kspr** [comment]
i have tested step 2 and the process is working perfectly
