### ISSUE TITLE
[Add Contact] Category should be using tagging 

### ISSUE THREAD

**Issue by upfounders** [upfounders/upfoundersAngular#8]
Please implement the tagging for the category. one user can have multiple tags, One person can be an investor and founder

**Comment by zaid4kspr** [comment]
if we want a contact to have many category we can just make the select with multiple choice and this require an additional work on the back but it won't be much work, if we want to implement the feature that allow us to put some new or old tags in  a contact this require more back end work than the first one and some front end updates

**Comment by upfounders** [comment]
As I mentioned long time back, this is lib we could use, https://github.com/Gbuomprisco/ngx-chips, we just need to apply the simplest
<img width="568" alt="Screen Shot 2020-02-19 at 8 13 41 PM" src="https://user-images.githubusercontent.com/59995322/74900375-6e3bea00-5354-11ea-8c00-e4e8c2a95932.png">
 case

**Comment by zaid4kspr** [comment]
![aa](https://user-images.githubusercontent.com/24481504/75090776-9bf87d00-5566-11ea-8fdf-4f1d7d1d58b4.png)
tags features added

**Comment by upfounders** [comment]
Awesome It’s great! 
When we have the tag , we don’t need category anymore, because this allow us to have assign more than one category to person so that one founder can be founder and developer, or founder and investor

**Comment by upfounders** [comment]
How much effort remove the category? just use the tagging to serve as the category

**Comment by zaid4kspr** [comment]
what i think about, that let's not mix between both let's keep category and tags may be a new feature like to filter with tags, removing category will require work on back end, front end, will crush the mobile app for missing attributes
